table Medidas
	lineageTag: fe86effe-16e7-4705-b093-08fe246e9b0c

	measure 'Qtde Mensagens' =
			
			
			DISTINCTCOUNT( fRegistros[mensagem] )
		formatString: 0
		lineageTag: 4f5c89d9-c0d6-4174-8332-0d61fdda13b9

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Coluna 1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

